### ISSUE TITLE
Getting java.lang.NoSuchMethodError: hidden.javax.xml.stream.XMLInputFactory.newFactory

### ISSUE THREAD

**Issue by pbthorste** [jenkinsci/nexus-platform-plugin#194]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.289.1
OS: Linux - 4.14.262-135.489.amzn1.x86_64
 ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Amazon linux 2

### Reproduction steps

Does not work in the latest version: 3.14.401.v1311ea_023ce5
But does work in version: 3.13.20220304-155321.e7fcac5

I am getting an exception when running the plugin, I don't really have enough info to deliver a good error report, sorry about that.

### Expected Results

No exception

### Actual Results

At first this appears:

```
Starting scanning target: /home/core/workspace/service_master/build/docker/main/layers/application.jar
Starting scanning target: /home/core/workspace/service_master/build/docker/main/layers/libs/HdrHistogram-2.1.12.jar
Starting scanning target: /home/core/workspace/service_master/build/docker/main/layers/libs/HikariCP-4.0.3.jar
```
And then this exception appears:

```java
java.lang.NoSuchMethodError: hidden.javax.xml.stream.XMLInputFactory.newFactory(Ljava/lang/String;Ljava/lang/ClassLoader;)Lhidden/javax/xml/stream/XMLInputFactory;
15:23:27  	at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:115)
15:23:27  	at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:101)
15:23:27  	at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:85)
15:23:27  	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:127)
15:23:27  	at org.cyclonedx.generators.xml.AbstractBomXmlGenerator.<init>(AbstractBomXmlGenerator.java:48)
15:23:27  	at org.cyclonedx.generators.xml.BomXmlGenerator13.<init>(BomXmlGenerator13.java:42)
15:23:27  	at org.cyclonedx.BomGeneratorFactory.createXml(BomGeneratorFactory.java:52)
15:23:27  	at hidden.com.sonatype.insight.scan.file.SbomUtils.createSbomXmlString(SbomUtils.java:38)
15:23:27  	at hidden.com.sonatype.insight.scan.file.MavenPomProcessor.process(MavenPomProcessor.java:65)
15:23:27  	at hidden.com.sonatype.insight.scan.file.ManifestContentProcessor.setScanItemContent(ManifestContentProcessor.java:292)
15:23:27  	at hidden.com.sonatype.insight.scan.file.FileVisitor.visitFile(FileVisitor.java:280)
15:23:27  	at hidden.com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:86)
15:23:27  	at hidden.com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
15:23:27  	at hidden.com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
15:23:27  	at hidden.com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
15:23:27  	at hidden.com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
15:23:27  	at hidden.com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
15:23:27  	at hidden.com.sonatype.insight.scan.file.FileWalker.walk(FileWalker.java:35)
15:23:27  	at hidden.com.sonatype.insight.scan.file.FileScanner.scan(FileScanner.java:93)
15:23:27  	at com.sonatype.nexus.api.iq.scan.Scanner.scanFiles(Scanner.java:158)
15:23:27  	at com.sonatype.nexus.api.iq.scan.Scanner.scan(Scanner.java:115)
15:23:27  	at com.sonatype.nexus.api.iq.impl.DefaultIqClient.scan(DefaultIqClient.java:255)
15:23:27  	at com.sonatype.nexus.api.iq.impl.DefaultIqClient.scan(DefaultIqClient.java:233)
15:23:27  	at com.sonatype.nexus.api.iq.internal.InternalIqClient$scan.call(Unknown Source)
15:23:27  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
15:23:27  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
15:23:27  	at org.sonatype.nexus.ci.iq.RemoteScanner.call(RemoteScanner.groovy:106)
15:23:27  	at org.sonatype.nexus.ci.iq.RemoteScanner.call(RemoteScanner.groovy)
15:23:27  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
15:23:27  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
15:23:27  	at hudson.remoting.Request$2.run(Request.java:376)
15:23:27  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
```

**Comment by headsail1** [comment]
I have the same problem on Jenkins 2.339.
Does not work in the latest version: 3.14.401.v1311ea_023ce5
But does work in version: 3.13.20220201-143240.3d657a5

**Comment by anderius** [comment]
This seems to be fixed in https://github.com/jenkinsci/nexus-platform-plugin/releases/tag/3.14.403.v07c2f1f96d60 :-)

**Comment by eduard-tita** [comment]
Re: https://github.com/jenkinsci/nexus-platform-plugin/pull/195
